services:
  postgres:
    container_name: imagedb_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "09282402911"
      POSTGRES_DB: imagedb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - albert_network

volumes:
  pgdata:
    name: pgdata

networks:
  albert_network:
    driver: bridge
